# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b334a63b297f17f4b649f3d43360adf6ff25c7e17290b5ea13a18a82513be77d3e7d194055ddc84a1ebfa7da7479212880103b9d76b5b7de1808bf174fb22470

test:
  secret_key_base: c82507da6def5ee0ea22f90cc7d6df28ea953c9994bf8bb5f3d2cd758b041aa78478c1e9d777af0ee69db3a31f5ea793c497202712f6fcf2c70ee7727a2cdb5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
